### ISSUE TITLE
Users shows undefined Email of tracked user

### ISSUE THREAD

**Issue by JigarAdesara1** [mixpanel/mixpanel-react-native#112]
On login, I have added the code for identifying the user like below

`mixpanel.identify(phone);`

Then I have registered some super properties like below

```
 mixpanel.registerSuperPropertiesOnce({
        email,
        phone,
        firstName,
        lastName
      });
```

Then I have set the User profile property by following the [Setting Profile Property document](https://developer.mixpanel.com/docs/react-native#setting-profile-properties) as below 

`mixpanel.getPeople().set("Email", email);`

In Mixpanel dashboard on Users module its shows undefined value of User profile like below Screenshot

![Screenshot 2021-11-29 at 10 17 04 AM](https://user-images.githubusercontent.com/87633274/143811715-dbf34913-fada-4c89-8d19-e5d7706ffafc.png)

Thanks in advance

**Comment by zihejia** [comment]
hi @JigarAdesara1 , Sorry for the late response. I see you're currently tracking an "email" property but the "Email" column in the table is mapped to the Mixpanel managed "$email" property (with the $ in front). Since you're not tracking "$email" with the $, the "Email" column in the table is returning undefined. You can actually modify your table columns to show the "email" property you currently track(by clicking `Edit Columns`). Feel free to let me know if you have more questions.
