### ISSUE TITLE
Notification Support

### ISSUE THREAD

**Issue by samuelbliss** [mixpanel/mixpanel-react-native#13]
I can't seem to find notification support anywhere in your documentation - is this feature available yet? Or is it slated for a later release?

If it is available, can we get the API documentation updated to reflect how to use it?

**Comment by kkelley-leftbrain** [comment]
Hey @samuelbliss - were you able to get any follow-up on this? Best I've seen so far is [the generic docs repo](https://developer.mixpanel.com/docs/push-notification), not sure if that helps at all in the short-term.

Cheers

**Comment by cohen72** [comment]
@samuelbliss I'm assuming this is due to the fact "Messages & Experiments" is no longer available to new customers, and evidently no reason to add support for it in this library.

See below the screenshot from [this thread](https://community.mixpanel.com/messages-13/where-did-the-messages-experiments-tab-go-4492)

![image](https://user-images.githubusercontent.com/1394233/104180829-742c3500-5416-11eb-9796-957398e7bfd3.png)

**Comment by zihejia** [comment]
Thanks @cohen72 .  

@samuelbliss @kkelley-leftbrain We are deprecating our Messages & Experiments so it's not available in the React Native SDK. I'm closing this issue now, sorry for the inconvenience.
