### ISSUE TITLE
getPeople.set doesn't work sometimes

### ISSUE THREAD

**Issue by MariaTolstov** [mixpanel/mixpanel-react-native#147]
We are using the 1.3.5 library in our client app, and we have discovered an issue recently where some of the users are missing properties, after calling mixpanel.identify and then mixpanel.getPeople.set to set the properties. The issue only happens sometimes, on IOS and Android. We suspect that there might be an issue with race condition between the calls, or something of that sort.

**Comment by zihejia** [comment]
Hi @MariaTolstov , this might be caused by a race condition. We released [v2.3.0](https://github.com/mixpanel/mixpanel-react-native/releases/tag/v2.3.0) which adds support for returning Promise for the identify(). Now you can do something like this 
```
     mixpanel.identify('Unique User ID').then(() => {
       // mixpanel.getPeople.set...
    }); 
```
Please try and feel free to reopen if the problem still exists.
