### ISSUE TITLE
New version and documentation updated for trackAutomaticEvents, but not typescript definition

### ISSUE THREAD

**Issue by MagicAce1988** [mixpanel/mixpanel-react-native#157]
Hi, 

I just realised there is a new update to the library where the documentation was also changed to also use a `trackAutomaticEvents` variable on mixpanel setup. However the typescript definition file was not updated so it throws an error. 

**Expected 1 argument and got 2.**

Not sure also what the trackAutomaticEvents setting is needed for as at the moments the automatic events seemed to be tracked automatically anyway?

**Comment by jaredmixpanel** [comment]
@MagicAce1988 a fix has been published in v2.0.1 - trackAutomaticEvents is required now because we no longer fetch the remote value for it from your project's settings, it can only be configured in code now. See the "Breaking Change" note here: https://github.com/mixpanel/mixpanel-react-native/releases/tag/v2.0.0
