### ISSUE TITLE
Initial registration / identity of Mixpanel user

### ISSUE THREAD

**Issue by kkelley-leftbrain** [mixpanel/mixpanel-react-native#16]
Good afternoon,

I've been following the progress of the library from Beta, so first and foremost congratulations on making the push to live!

Quick disclosure - I haven't cut over from the use of the beta bundle (i.e. `mixpanel-react-native-1.0.0-beta.5.tgz`) as of yet - this could potentially be part of the issue, but the code doesn't seem to have changed in the time this has gone live.

I [made a post ](https://community.mixpanel.com/react-native-shipped-40/handling-user-identity-best-practices-with-identity-merge-4930) concerning the use of `identify` and `alias` recently, and am now currently following [the documentation ](https://developer.mixpanel.com/docs/react-native#combining-anonymous-and-identifiable-user-data) in hopes of locking down a clean implementation across the board. It seems like per the formal docs, there's an extra step from that thread reply.

So, after our first-time login (following a welcome email, temp password, etc.), I am attempting to follow verbatim the snippet provided:

``` javascript
// This makes the current ID (by default an auto-generated GUID)
// and '13793' interchangeable distinct ids (but not retroactively).
mixpanel.alias("13793", null);
// To create a user profile, you must call identify()
mixpanel.identify(mixpanel.getDistinctId());
```

However, I'm getting an error following this example.  The caveat here is that I'm attempting a new user on the same device (emulator) so there might be a snag in the issue I'm experiencing. 

![image](https://user-images.githubusercontent.com/71667995/103697558-b280aa80-4f65-11eb-8a33-bd048d39af2c.png)

It looks like even though I made a call to `reset()` during the logout (followed by a `flush()` to ensure this is prioritized) I am either caching or hanging onto the former login of `kkelley` rather than the expected GUID-style unique_ID that Mixpanel typically generates. 

Have I missed a step in registration setup following these best practices? I'm very plausibly creating a niche scenario trying to attempt this back to back on the device, but I suppose this could be replicated if two users shared a device as well, which is a bit more likely. Let me know if I've left any info out as well, and thank you for your time.

Cheers

**Comment by kkelley-leftbrain** [comment]
Update on this one:

After upgrading to the live version (1.0.1 as of this writing), definitely noted some stark differences in the main index.js file, so boo on me for not having done that before asking. However, the approach in the [aforementioned docs](https://developer.mixpanel.com/docs/react-native#combining-anonymous-and-identifiable-user-data) regarding aliasing as a one-time lifecycle event per user still don't seem to work as-is. I tinkered with alternatives like 

``` javascript
mixpanel.alias("kkelley", mixpanel.getDistinctId())
```

or switching the order of the two calls mentioned above, but to no avail. In the updated  version, the issue becomes a `distinctIdunefined`error, which I am assuming comes from the second alias param being null and `getDistinctId()` not having a reliable input at that time either?

In any event, I'm grasping at straws so I guess I can boil it down to a couple of more pointed questions:

1. Is aliasing a beneficial or otherwise necessary step in user identity? 
2. The reply left by Cassandra made things seem like `identify()` per login and `reset()` per logout should do the trick - is that in fact enough to manage a user of the lifetime of an application (app versions, multiple devices, etc)?
3. If the attempt I'm making above which involves ailasing is accurate, are the errors I am getting intended behavior or is there a tweak that needs to be made under the hood?

Cheers

**Comment by zihejia** [comment]
Hi @kkelley-leftbrain ,

answering your questions, so others can benefit too.

1) Is aliasing a beneficial or otherwise necessary step in user identity?

As long as [ID merge is enabled in your project](https://help.mixpanel.com/hc/en-us/articles/360039133851-Moving-to-Identity-Merge#enable-id-merge), there is no benefit to implementing alias alongside of Identify when a user creates an account. Identify will suffice.

2) The reply left by Cassandra made things seem like identify() per login and reset() per logout should do the trick - is that in fact enough to manage a user of the lifetime of an application (app versions, multiple devices, etc)?

Same as above.

3) If the attempt I'm making above which involves aliasing is accurate, are the errors I am getting intended behavior or is there a tweak that needs to be made under the hood?

Sorry about the inconvenience. I will update the doc, the distinct id should not be null. and `mixpanel.getDistinctId()` is a promise, should be used like this,
```
        this.mixpanel.getDistinctId().then(distinctId => {
            this.mixpanel.alias("new id", distinctId);
        });
```
or 
```
const distinctId = await this.mixpanel.getDistinctId(); 
this.mixpanel.alias("new id", distinctId);
```
Also I could not replicate the reset issue. The reset should use a newly generated distinct id on the device. Is there any chance in your code the `identify` has been called immediately after the reset with the id “kkeley” by accident?

**Comment by kkelley-leftbrain** [comment]
Thanks so much for the reply @zihejia - I think you are correct that the kkelley anonymous ID persisting may have either been transient from the beta package or due to improper testing.

The scenario that I am now dealing with is that live app-version using the beta package seems to be identifying in reverse, where I see all user activity listed as a generated GUID-style ID, with a "before identity" field and "userID" field holding the userID I used identify with.
![image](https://user-images.githubusercontent.com/71667995/105917707-5820ba00-5ff8-11eb-9cc7-b12d89499f78.png)

![image](https://user-images.githubusercontent.com/71667995/105917196-a5e8f280-5ff7-11eb-9e23-729364e27a4f.png)

So... probably a right place wrong time scenario on that front. Do you know if I will be able to reconcile those IDs with subsequent `idenfity` calls once the current version is live on the apps being used?

Cheers

**Comment by cassiegamm** [comment]
Hi @kkelley-leftbrain,

I'm struggling to understand your question. Could you outline what you expect to happen, vs what you are observing?

There's not a directionality to identify per say... If you call reset, trigger an event, then call identify, trigger another event all these events will be attributed to the same user & user profile. 

best,
Cassie

PS: It may be worth transitioning this conversation to [support](https://help.mixpanel.com/hc/en-us/requests/new) as then you could share links to your examples so they can look at your data and address specifics rather than generalities.

**Comment by kkelley-leftbrain** [comment]
Hey @cassiegamm thanks for the reply.

So based on some sandbox tests, my expectation is that when a user (new or existing) boots up the app and is met with a login prompt, they'll go through the `identify` that I've placed and fed with their company-specific username/identifier.

The confusion that I'm having is that _instead_ of that, I'm seeing that the GUID-style mixpanelID is being used, and the username is registered as that "DistinctID before Identity" field. I haven't tried any work with cohorts or other filters as of yet, but for readability-sake, this doesn't seem quite right (when the non-devs at my company actually need to interact with these users, that is).

t;ldr
I tried to illustrate in the image above using some live-data with my generic info instead - the identity seems "backwards" in the current implementation of our live app (which has yet to be updated with the live version of the mixpanel library). Have I gotten our users stuck in a bad state?
