### ISSUE TITLE
Issue with mixpanel dashboard and distinctId

### ISSUE THREAD

**Issue by makarkotlov** [mixpanel/mixpanel-react-native#196]
On the mixpanel dashboard the `distinctId` for the user is set to `$device:551d5226-72ab-409f-b8bc-3c0f94815d87` but in the app the `getDistinctId` function returns `a06e57b2-5fcf-43c5-8b11-73b80f28f949`. The `Distinct ID Before Identity` field seems to be also incorrect since the distinctId before the call of the `identify` function was `$device:551d5226-72ab-409f-b8bc-3c0f94815d87`

<img width="924" alt="image" src="https://github.com/mixpanel/mixpanel-react-native/assets/32848434/dac52786-b4c1-4ffd-8e1b-7148b1be0f6d">

STR:
1. Open an app
2. Identify a user
3. Call the reset function (which generates a new deviceId which is then set as distinctId)
4. Identify the same user

Lib version: 2.2.5
RN version: 0.69.9

**Comment by zihejia** [comment]
hi @makarkotlov ,  It seems your case falls into the 'returning user' category. Please refer to the Mixpanel documentation on [identifying users](https://docs.mixpanel.com/docs/tracking/how-tos/identifying-users#returning-user). This issue is unlikely to be related to the SDK. Could you please reach out to [Mixpanel support](https://docs.mixpanel.com/docs/other-bits/support-and-community/support)? They will provide you with more details on user ID management.
