### ISSUE TITLE
MixpanelReactNative is null

### ISSUE THREAD

**Issue by danlupascu** [mixpanel/mixpanel-react-native#88]
I'm getting this error when trying to run the app on an android emulator.

This issue has been opened a few times before but it was closed every time for some reason.

I'm using new instance method `init` and it's stil not working.

I'm creating the instance in a file `src/utils/mixpanel`
```javascript
import Config from 'react-native-config';
import { Mixpanel } from 'mixpanel-react-native';

// @ts-ignore
export default new Mixpanel(Config.MIXPANEL_TOKEN);
```

and somewhere in the app
```javascript
import mixpanel from '../utils/mixpanel';

mixpanel.init().then(() => {});
```

Here's the error from the terminal:
```
Error: mixpanel-react-native: MixpanelReactNative is null. 
    Please follow the guide on the Github repository: https://github.com/mixpanel/mixpanel-react-native
```

**Comment by jckw** [comment]
Did you run `pod install` and rebuild the app?

**Comment by danlupascu** [comment]
Yes, but this has nothing to do with iOS. This problem is on Android only. Works fine on iOS.

**Comment by Jy411** [comment]
I am getting this error when running tests with jest.

**Comment by tronin** [comment]
The same problem on iOS

**Comment by p1yu5h** [comment]
@Jy411 You can mock `mixpanel-react-native` like so:
```
jest.mock("mixpanel-react-native", () => ({
  __esModule: true,
  default: () => jest.fn(),
  Mixpanel: jest.fn(() => ({
    init: jest.fn(),
  })),
}));
```

**Comment by zihejia** [comment]
Please try the latest version v1.3.5. If anyone still has the problem, please feel free to reopen it. In most cases, this is due to integration issues, the code is executed before MixpanelReactNative is available.

When that happens, cleaning the environment, restarting the react-native server can solve a lot of troubles. If still not working, you may have some problems with your code or the way Mixpanel is integrated.

To enable us to assist you a bit easier, for debugging, we suggest trying to integrate Mixpanel on the minimum possible app(i.e. based on `npx react-native init AwesomeProject` is perfect), you can check our instructions or have a look at the sample apps we provided(under Samples directory, we provided three samples). All samples from us should work and if you copy the way the sample does on top of the minimum template `AwesomeProject`, it should also work. If you still experience issues or you use your own way of integration and it's not working, please attach the sample app here, we will be able to help you very quickly. But the code snippet does not provide enough information due to the nature of React Native Projects, just too many dependencies and variations that anything could go wrong.

**Comment by buddabic2** [comment]
Hey @zihejia,

I'm facing the same issue on a minimalistic app and don't really understand how to fix it. 

```
Error: mixpanel-react-native: MixpanelReactNative is null. 
Please follow the guide on the Github repository: https://github.com/mixpanel/mixpanel-react-native.
```

I installed the version ^1.3.10 and followed all of the previously raised threads but none of the fixes is helping. Could you please take a look at it? https://github.com/buddabic2/test-mixpanel

**Comment by bernatbombi** [comment]
I solved this by manually adding the library:

```
//settings.gradle
include ':mixpanel-react-native'
project(':mixpanel-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/mixpanel-react-native/android')
```

```
//build.gradle
implementation project(':mixpanel-react-native')
```

```
//MainApplication.java 
import com.mixpanel.reactnative.MixpanelReactNativePackage;
```

```
//MainApplication.java getPackages
new MixpanelReactNativePackage(),
```

**Comment by T-Damer** [comment]
> I solved this by manually adding the library:
> 
> ```
> //settings.gradle
> include ':mixpanel-react-native'
> project(':mixpanel-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/mixpanel-react-native/android')
> ```
> 
> ```
> //build.gradle
> implementation project(':mixpanel-react-native')
> ```
> 
> ```
> //MainApplication.java 
> import com.mixpanel.reactnative.MixpanelReactNativePackage;
> ```
> 
> ```
> //MainApplication.java getPackages
> new MixpanelReactNativePackage(),
> ```

Which version of RN did you use? Tried same patches, it didn't work, having same issue :thinking: 
Looks like it can't load module implementation
